# Generated by Django 4.1.7 on 2023-03-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Reception',
            fields=[
                ('session_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('session_data', models.CharField(max_length=200)),
                ('expire_data', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'login_session',
                'db_table': 'session_reception',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[(0, '男'), (1, '女')], default=0, max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('posts', models.CharField(max_length=20)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user_msg',
                'db_table': 'user',
            },
        ),
    ]
